spring:
  application:
    name: weather-app
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherdb
    username: postgres
    password: ''
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

openweather:
  api-key: f9c8a98ced7e37866436f764c3b830d9
  base-url: https://api.openweathermap.org
  geocoding-path: /geo/1.0/direct
  weather-path: /data/2.5/weather

jwt:
  secret: ${JWT_SECRET:6olHddRHkVqld853s3MKhxYEyz8yY3NUjC5LV1anGvgYuu+j7d5sKIO3aVuCcW8Y09Z5PlctSMrms/vLV4IEUg==}
  expiration: ${JWT_EXPIRATION:900000}